'use strict';
let step=1;
let completedOrder=null;
const customer={name:'',email:'',phone:'',street:'',barangay:'',city:'',province:'',postal:'',payment:''};
const panel=document.getElementById('checkout-panel');
const sidebar=document.getElementById('order-sidebar');
const fieldInfo={name:['Full name','Your full name','name'],email:['Email address','you@example.com','email'],phone:['Phone number','0917 123 4567','tel'],street:['House number / Street','123 Mabini Street','address-line1'],barangay:['Barangay','Barangay name','address-line2'],city:['City / Municipality','City or municipality','address-level2'],province:['Province','Province or Metro Manila','address-level1'],postal:['Postal code','4-digit postal code','postal-code']};
function field(key){const [label,placeholder,autocomplete]=fieldInfo[key];return `<div class="form-field"><label for="${key}">${label} <span>*</span></label><input id="${key}" name="${key}" type="${key==='email'?'email':key==='phone'?'tel':'text'}" ${key==='postal'?'inputmode="numeric" maxlength="4"':''} autocomplete="${autocomplete}" placeholder="${placeholder}" value="${escapeHTML(customer[key])}" required aria-describedby="${key}-error"><p class="field-error" id="${key}-error"></p></div>`;}
function validation(key,value){if(!value.trim())return `${fieldInfo[key][0]} is required.`;if(key==='name'&&value.trim().length<2)return 'Enter at least 2 characters for your name.';if(key==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))return 'Enter a valid email address.';if(key==='phone'&&!/^(09\d{9}|\+639\d{9})$/.test(value.replace(/[\s()-]/g,'')))return 'Use a Philippine mobile number: 09XXXXXXXXX or +639XXXXXXXXX.';if(key==='postal'&&!/^\d{4}$/.test(value))return 'Enter a 4-digit Philippine postal code.';return '';}
function validateField(input){const error=validation(input.name,input.value);document.getElementById(`${input.name}-error`).textContent=error;input.setAttribute('aria-invalid',!!error);return !error;}
function totals(subtotal,shipping){return `<div><span>Subtotal</span><strong>${money(subtotal)}</strong></div><div><span>Shipping</span><span>${shipping?money(shipping):'Free'}</span></div><div class="grand-total"><span>Total</span><strong>${money(subtotal+shipping)}</strong></div>`;}
function lines(items){return items.map(i=>`<article class="review-item"><img src="${i.product.image}" alt="${i.product.name}"><div><h3>${i.product.name}</h3><p>${i.product.color} · Size ${i.size} · Qty ${i.quantity}</p><p>${money(i.product.price)} each</p></div><strong>${money(i.product.price*i.quantity)}</strong></article>`).join('');}
function address(data){return `${escapeHTML(data.street)}, ${escapeHTML(data.barangay)}<br>${escapeHTML(data.city)}, ${escapeHTML(data.province)} ${escapeHTML(data.postal)}<br>Philippines`;}
function render(){
 document.querySelectorAll('.steps li').forEach((li,i)=>{li.classList.toggle('current',i+1===step);li.classList.toggle('done',i+1<step);if(i+1===step)li.setAttribute('aria-current','step');else li.removeAttribute('aria-current');});
 if(!Cart.count()&&!completedOrder){panel.innerHTML='<div class="empty-state"><h2>Your bag is empty.</h2><p>Add your favorite tees before starting checkout.</p><a href="index.html#products" class="button">Find your everyday ↗</a></div>';sidebar.hidden=true;return;}
 sidebar.hidden=step===5;
 sidebar.innerHTML=`<p class="eyebrow">A GOOD DAILY ROTATION</p><h2>Your order <span>(${Cart.count()})</span></h2>${Cart.getItems().map(i=>`<div class="sidebar-item"><img src="${i.product.image}" alt="${i.product.name}"><div><strong>${i.product.name}</strong><small>Size ${i.size} · Qty ${i.quantity}</small></div><span>${money(i.product.price*i.quantity)}</span></div>`).join('')}<div class="cart-totals">${totals(Cart.subtotal(),Cart.shipping())}</div><p class="product-note">Free shipping on orders ₱2,000+.<br>Standard shipping is ₱120.</p><a href="index.html#products" class="text-link">← Edit your bag at the store</a>`;
 if(step<=2){const keys=step===1?['name','email','phone']:['street','barangay','city','province','postal'];panel.innerHTML=`<p class="eyebrow">STEP 0${step} / 05</p><h2 id="step-title" tabindex="-1">${step===1?'First, a little about you.':'Where should they go?'}</h2><p>${step===1?'Your details for this demo order.':'Enter your shipping address in the Philippines.'}</p><form id="step-form" novalidate>${keys.map(field).join('')}<div class="checkout-actions">${step===2?'<button type="button" class="text-link" data-back>← Back</button>':'<a href="index.html" class="text-link">← Store</a>'}<button class="button" type="submit">${step===1?'Shipping information':'Review your order'} ↗</button></div></form>`;const form=document.getElementById('step-form');form.addEventListener('input',e=>{if(e.target.name){customer[e.target.name]=e.target.value;validateField(e.target);}});form.addEventListener('submit',e=>{e.preventDefault();const inputs=[...form.querySelectorAll('input')];inputs.forEach(i=>customer[i.name]=i.value.trim());const checks=inputs.map(validateField);if(checks.every(Boolean)){step++;render();}else inputs[checks.indexOf(false)].focus();});}
 if(step===3)panel.innerHTML=`<p class="eyebrow">STEP 03 / 05</p><h2 id="step-title" tabindex="-1">Looking good.</h2><p>Take a moment to check the details.</p>${lines(Cart.getItems())}<div class="review-details"><div><h3>Customer <button class="text-link" data-go="1">Edit</button></h3><p>${escapeHTML(customer.name)}<br>${escapeHTML(customer.email)}<br>${escapeHTML(customer.phone)}</p></div><div><h3>Ship to <button class="text-link" data-go="2">Edit</button></h3><p>${address(customer)}</p></div></div><div class="cart-totals">${totals(Cart.subtotal(),Cart.shipping())}</div><div class="checkout-actions"><button class="text-link" data-back>← Back</button><button class="button" data-next>Choose payment ↗</button></div>`;
 if(step===4){panel.innerHTML=`<p class="eyebrow">STEP 04 / 05</p><h2 id="step-title" tabindex="-1">One last thing.</h2><p>Select a simulated payment method. No money will be charged.</p><form id="payment-form" novalidate><fieldset class="payment-options"><legend>Payment method *</legend>${[['Cash on Delivery','Pay on delivery — simulated'],['GCash','Mobile wallet — simulated'],['Maya','Mobile wallet — simulated']].map(([name,description])=>`<label><input type="radio" name="payment" value="${name}" ${customer.payment===name?'checked':''} aria-describedby="payment-error"><span><strong>${name}</strong><small>${description}</small></span><span class="payment-symbol">${name==='Cash on Delivery'?'₱':name==='GCash'?'G':'m'}</span></label>`).join('')}</fieldset><p id="payment-error" class="field-error" role="alert"></p><div class="demo-box">This is a frontend demonstration. Do not enter wallet numbers, PINs, or payment credentials.</div><div class="checkout-actions"><button type="button" class="text-link" data-back>← Back</button><button type="submit" class="button">Place demo order · ${money(Cart.subtotal()+Cart.shipping())} ↗</button></div></form>`;document.getElementById('payment-form').addEventListener('change',e=>{customer.payment=e.target.value;document.getElementById('payment-error').textContent='';});document.getElementById('payment-form').addEventListener('submit',e=>{e.preventDefault();if(!customer.payment){document.getElementById('payment-error').textContent='Please select a payment method.';panel.querySelector('input').focus();return;}if(!Cart.count()){render();return;}const random=new Uint32Array(2);crypto.getRandomValues(random);completedOrder={number:`FORM-${new Date().toISOString().slice(0,10).replace(/-/g,'')}-${Array.from(random,n=>n.toString(36)).join('').slice(0,10).toUpperCase()}`,customer:{...customer},items:Cart.getItems(),subtotal:Cart.subtotal(),shipping:Cart.shipping()};Cart.clear();step=5;render();});}
 if(step===5){const order=completedOrder;document.getElementById('checkout-layout').classList.add('confirmed');document.getElementById('checkout-title').textContent='Good things are on the way.';panel.innerHTML=`<div class="confirmation-head"><span class="success-icon">✓</span><p class="eyebrow">DEMO ORDER SUCCESSFULLY PLACED</p><h2 id="step-title" tabindex="-1">Thank you, ${escapeHTML(order.customer.name)}.</h2><p>Your new daily rotation looks good on you.</p><strong class="order-number">${order.number}</strong><p class="product-note">This confirmation is for demonstration only. No order is shipped and no email is sent.<br>Print or save this page before leaving to keep your confirmation.</p></div>${lines(order.items)}<div class="review-details"><div><h3>Shipping address</h3><p>${escapeHTML(order.customer.name)}<br>${address(order.customer)}</p></div><div><h3>Payment method</h3><p>${escapeHTML(order.customer.payment)}<br>Simulated payment</p></div></div><div class="cart-totals">${totals(order.subtotal,order.shipping)}</div><div class="checkout-actions"><button class="text-link" id="print-order">Print confirmation</button><a href="index.html" class="button">Continue shopping ↗</a></div>`;document.getElementById('print-order').addEventListener('click',()=>window.print());}
 panel.querySelectorAll('[data-back]').forEach(b=>b.addEventListener('click',()=>{step--;render();}));panel.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>{step=Number(b.dataset.go);render();}));panel.querySelector('[data-next]')?.addEventListener('click',()=>{step++;render();});document.getElementById('step-title')?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'smooth'});
}
render();
