'use strict';
const grid=document.getElementById('product-grid');
const productModal=document.getElementById('product-modal');
const cartModal=document.getElementById('cart-modal');
function renderProducts(filter='all'){
 const products=StoreProducts.filter(p=>filter==='all'||p.category===filter);
 document.getElementById('product-count').textContent=`${products.length} thoughtfully made essentials`;
 grid.innerHTML=products.map((p)=>`<article class="product-card"><button class="product-image" data-product="${p.id}" aria-label="View ${p.name}"><img src="${p.image}" alt="${p.name} in ${p.color}" loading="lazy">${p.badge?`<span class="product-badge">${p.badge}</span>`:''}<span class="image-arrow">↗</span></button><div class="product-title"><h3>${p.name}</h3><span>${money(p.price)}</span></div><div class="product-color"><span style="background:${p.hex}"></span>${p.color} <span class="fit-label">S — XL</span></div><p>${p.description}</p><div class="card-actions"><button class="text-link" data-product="${p.id}">View Product ↗</button><button class="small-button" data-product="${p.id}" data-intent="buy">Buy Now</button><button class="small-button filled" data-product="${p.id}" data-intent="add">Add to Cart</button></div></article>`).join('');
}
function openProduct(id,intent='view'){
 const p=StoreProducts.find(p=>p.id===id);if(!p)return;
 document.getElementById('modal-content').innerHTML=`<div class="modal-image"><img src="${p.image}" alt="${p.name} in ${p.color}"></div><div class="modal-details"><p class="eyebrow">FORM / EVERYDAY COLLECTION</p><h2 id="modal-name">${p.name}</h2><p class="modal-price">${money(p.price)}</p><p>${p.detail}</p><p class="product-color"><span style="background:${p.hex}"></span>Color: ${p.color}</p><form id="product-form" novalidate><fieldset class="size-options"><legend>Choose your size <span aria-hidden="true">*</span></legend>${p.sizes.map(size=>`<label><input type="radio" name="size" value="${size}" required><span>${size}</span></label>`).join('')}</fieldset><p class="field-error" id="size-error" role="alert"></p><details class="size-chart"><summary>Size guide · measurements in cm</summary><table><caption>Garment measurements · allow ±2 cm</caption><thead><tr><th>Size</th><th>Chest</th><th>Length</th></tr></thead><tbody><tr><th>Small</th><td>96</td><td>68</td></tr><tr><th>Medium</th><td>102</td><td>71</td></tr><tr><th>Large</th><td>108</td><td>74</td></tr><tr><th>Extra Large</th><td>114</td><td>77</td></tr></tbody></table></details><label class="quantity-label" for="product-quantity">Quantity</label><div class="quantity-control"><button type="button" data-quantity="-1" aria-label="Decrease quantity">−</button><input type="number" id="product-quantity" min="1" max="99" value="1" aria-describedby="quantity-error"><button type="button" data-quantity="1" aria-label="Increase quantity">+</button></div><p class="field-error" id="quantity-error" role="alert"></p><div class="modal-actions"><button type="submit" class="button" value="add">Add to Cart ↗</button><button type="submit" class="button outline" value="buy">Buy Now</button></div><p class="product-note">Free shipping from ₱2,000 · ₱120 standard shipping</p></form></div>`;
 const form=document.getElementById('product-form');
 form.addEventListener('change',()=>{document.getElementById('size-error').textContent='';});
 form.querySelectorAll('[data-quantity]').forEach(b=>b.addEventListener('click',()=>{const input=document.getElementById('product-quantity');input.value=Math.max(1,Math.min(99,(Number(input.value)||1)+Number(b.dataset.quantity)));document.getElementById('quantity-error').textContent='';}));
 document.getElementById('product-quantity').addEventListener('input',e=>{if(Number.isInteger(Number(e.target.value))&&e.target.value>=1&&e.target.value<=99)document.getElementById('quantity-error').textContent='';});
 form.addEventListener('submit',e=>{e.preventDefault();const size=new FormData(form).get('size');const quantity=Number(document.getElementById('product-quantity').value);if(!size){document.getElementById('size-error').textContent='Please select a size before continuing.';form.querySelector('input[name="size"]').focus();return;}try{Cart.add(p.id,size,quantity);if(e.submitter?.value==='buy'){window.location.href='checkout.html';return;}productModal.close();notify(`${p.name} (${size}) added to your bag.`);}catch(error){document.getElementById('quantity-error').textContent=error.message;}});
 productModal.showModal();
 if(intent!=='view'){document.getElementById('size-error').textContent=`Choose a size, then ${intent==='buy'?'Buy Now':'Add to Cart'} to continue.`;form.querySelector('input[name="size"]').focus();}
}
function renderCart(){
 const items=Cart.getItems();
 document.getElementById('cart-content').innerHTML=items.length?`<div class="cart-items">${items.map(i=>`<article class="cart-item"><img src="${i.product.image}" alt="${i.product.name}"><div><h3>${i.product.name}</h3><p>${i.product.color} · ${money(i.product.price)} each</p><div class="cart-controls"><label>Size <select data-resize="${i.id}" data-size="${i.size}">${i.product.sizes.map(s=>`<option ${s===i.size?'selected':''}>${s}</option>`).join('')}</select></label><label>Qty <input aria-label="Quantity for ${i.product.name}" type="number" min="1" max="99" value="${i.quantity}" data-update="${i.id}" data-size="${i.size}"></label></div><button class="remove-button" data-remove="${i.id}" data-size="${i.size}">Remove</button></div><strong>${money(i.product.price*i.quantity)}</strong></article>`).join('')}</div><div class="cart-totals"><div><span>Subtotal</span><strong>${money(Cart.subtotal())}</strong></div><div><span>Shipping</span><span>${Cart.shipping()?money(Cart.shipping()):'Free'}</span></div><div class="grand-total"><span>Total</span><strong>${money(Cart.subtotal()+Cart.shipping())}</strong></div><p>${Cart.shipping()?`${money(2000-Cart.subtotal())} away from free shipping.`:'Your order qualifies for free shipping.'}</p><a href="checkout.html" class="button">Proceed to checkout ↗</a><small>Demo checkout. No real payment required.</small></div>`:`<div class="empty-state"><span>↗</span><h3>Your next favorite is waiting.</h3><p>Your shopping bag is empty. Add a tee to get started.</p><button class="button" data-close-cart>Explore the collection</button></div>`;
}
document.addEventListener('click',e=>{const product=e.target.closest('[data-product]');if(product)openProduct(product.dataset.product,product.dataset.intent);if(e.target.closest('[data-open-cart]')){renderCart();cartModal.showModal();}if(e.target.closest('[data-close-cart]'))cartModal.close();if(e.target.closest('[data-close-product]'))productModal.close();const remove=e.target.closest('[data-remove]');if(remove){Cart.remove(remove.dataset.remove,remove.dataset.size);notify('Product removed from your bag.');}});
document.getElementById('cart-content').addEventListener('change',e=>{if(e.target.matches('[data-update]')){if(!Cart.update(e.target.dataset.update,e.target.dataset.size,Number(e.target.value))){notify('Choose a whole quantity from 1 to 99.');renderCart();}}if(e.target.matches('[data-resize]')){Cart.resize(e.target.dataset.resize,e.target.dataset.size,e.target.value);renderCart();}});
document.addEventListener('cartchange',renderCart);
[productModal,cartModal].forEach(modal=>modal.addEventListener('click',e=>{const rect=modal.getBoundingClientRect();if(e.target===modal&&(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom))modal.close();}));
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',b===button);});renderProducts(button.dataset.filter);}));
const menu=document.querySelector('.menu-toggle');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',open);document.querySelector('nav').classList.toggle('open',open);});document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');document.querySelector('nav').classList.remove('open');}));
renderProducts();
