'use strict';
window.StoreProducts = [
  {id:'p01',name:'The Everyday Tee',price:590,color:'Chalk',hex:'#eeeae0',category:'essential',badge:'BESTSELLER',description:'The one you’ll reach for. Every single day.',detail:'A clean crew neck with a relaxed, straight fit. Soft cotton jersey and a considered length make this the foundation of your daily rotation.'},
  {id:'p02',name:'The Off-Duty Tee',price:650,color:'Forest',hex:'#3c5346',category:'essential',badge:'A LITTLE MORE RELAXED',description:'An easy fit for your slower moments.',detail:'Dropped shoulders and a roomy silhouette in a grounded forest green. A substantial cotton feel with plenty of room to move.'},
  {id:'p03',name:'The Sunday Tee',price:590,color:'Oat',hex:'#cabc9c',category:'essential',description:'Soft, warm, and in absolutely no rush.',detail:'A warm neutral crew neck inspired by slow mornings. A regular fit with soft seams and a versatile shade that goes with your favorite denim.'},
  {id:'p04',name:'The After Hours Tee',price:650,color:'Washed black',hex:'#333331',category:'essential',description:'Your everyday staple, after dark.',detail:'A washed black essential with a relaxed fit, ribbed neckline, and understated character. Easy to dress up or keep casual.'},
  {id:'p05',name:'The Daybreak Tee',price:620,color:'Butter',hex:'#e6d58d',category:'essential',badge:'A BRIGHTER BASIC',description:'A little sunshine for your wardrobe.',detail:'A soft butter yellow tee with an easy regular fit. Subtle color and a comfortable cotton feel for a fresh start to your day.'},
  {id:'p06',name:'The Good Form Tee',price:750,color:'Chalk / forest',hex:'#eeeae0',category:'graphic',print:'good form.',description:'Good days begin with good form.',detail:'Our signature wordmark in forest green on a chalk base. An oversized silhouette with a playful front print and a classic crew neckline.'},
  {id:'p07',name:'The Coastline Tee',price:650,color:'Slate blue',hex:'#8a9da7',category:'essential',description:'A breath of fresh air. In T-shirt form.',detail:'Muted coastal blue meets an easy, relaxed shape. The kind of cotton tee that travels from a city morning to a beach afternoon.'},
  {id:'p08',name:'The Slow Living Tee',price:790,color:'Clay',hex:'#ae7763',category:'graphic',print:'slow living',description:'Take your time. Find your own rhythm.',detail:'Earthy clay with a simple cream graphic. A relaxed cut with dropped shoulders, made for taking the scenic route.'},
  {id:'p09',name:'The Field Notes Tee',price:750,color:'Sage',hex:'#a8ae97',category:'graphic',print:'FIELD NOTES',description:'For the curious. And the wandering.',detail:'A sage green graphic tee inspired by little outdoor discoveries. A small typographic chest print on a regular, comfortable fit.'},
  {id:'p10',name:'The Studio Tee',price:790,color:'Ink',hex:'#38424b',category:'graphic',print:'FORM / 01',description:'A blank canvas for whatever comes next.',detail:'Deep ink cotton with our studio edition graphic. A roomy fit and sturdy ribbed neck bring an artful touch to an everyday essential.'}
].map((p,i)=>({...p,image:`images/product-images/${String(i+1).padStart(2,'0')}.svg`,sizes:['S','M','L','XL']}));
window.money = value => new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:2}).format(value);
window.escapeHTML = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
